### ISSUE TITLE
iOS 15.7 (19H12)

### ISSUE THREAD

**Issue by julienreszka** [filsv/iOSDeviceSupport#149]
Hello, does anybody have the zip for iOS 15.7 (19H12)?
Thanks

**Comment by SimonGoodwin** [comment]
Thanks Suyraj - I've downloaded the xcode you suggest and unpacked all 23 GB of it, but alas it does not contain 15.7 - it has versions up to 15.5 then skips to 16.0

Can anyone else help Julien and me?

The problem here is that 15.7 is the end of the line for my iPhone 7+ and the only available update. Corporate IT has pushed me onto that and now I can't test anything locally.

I've tried snarfing 15.6 and renaming it to 15.7 but unsurprisingly that didn't work. Still getting "Please try rebooting and reconnecting the device. (0xE8000076)" when I try to deploy a successful Xcode build to the phone. Rebooting and reconnecting doesn't help.

**Comment by SimonGoodwin** [comment]
The Xcode 14.0.1 on the Apple site has this in the "General
Resolved Issues"
Fixed: Xcode 14 cannot be used with devices running iOS 15.7. (99847608)

But AFAICS there's only DeviceSupport for 15.0/2/4/5 and 16.0 in there

I'm trying Xcode 14.1 beta 2 now.

**Comment by fisforfaheem** [comment]
i have xcode but i accidently update my iphone 7 plus to ios 15.7 please help me with a fix

**Comment by SimonGoodwin** [comment]
If you have Xcode 14.1 you don't need a fix. So I infer you need to download that version, from the link above. 'i have xcode' doesn't help at all. The **specific version** is crucial, and if you can't install it (as Apple don't support it on your OS) you need to download the package (currently at https://developer.apple.com/download/applications/ as noted above), open it and copy the Device Support for 15.7 into your existing Xcode installation. You will need to Show Package Contents on both Xcode apps then search to find where it goes.

**Comment by fisforfaheem** [comment]
I have Xcode 13 on Big sur



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
01/12/22,
01:35:57

**Comment by filsv** [comment]
@julienreszka @soorajpandey @SimonGoodwin @fisforfaheem Guys here iOS 15.7 Support Files - [Download](https://github.com/filsv/iOSDeviceSupport/raw/master/15.7.zip).
