### ISSUE TITLE
iOS 12.5.7 not showing in Xcode 15.2

### ISSUE THREAD

**Issue by Kwanzoe** [filsv/iOSDeviceSupport#191]
Please share the iOS 12.5.7 support file for Xcode 15.2

**Comment by filsv** [comment]
@Kwanzoe Xcode 15 no longer supports iOS 12 as a deployment target because Apple has dropped support for older iOS versions in its latest Xcode updates. The minimum deployment target is usually updated with new Xcode releases, and Apple typically supports iOS versions that are still receiving security updates and are widely used on current devices. As of Xcode 15, the minimum iOS deployment target has been raised to iOS 13 or newer, which is why iOS 12 does not appear as an option.

If you still need to develop or maintain an app for iOS 12, you’ll need to use an older version of Xcode (such as Xcode 14) that still supports iOS 12.
